form.js, register.html, style.css
registration page added plus some basic validation done
=> Ltp 13 program registration page

index.html, style.css
Adding basic functionality to register with Auth code, very messy as this is a temp fix for the prototype and once we have further info on the db I shall implement this properly with the DB.
=> Lpt 14 auth code

register.html, registerNewUserProcess.php, signInCredentials.php, users.txt
The addition of a user file will allow the register page to add users.
=> Refined Login Functionality

dashboard.php, projects.php
Found that using the navbar class with fixed-bottom behaved nicer than plain footer class.
=> Forced footer to bottom of page

productivity/processAddTaskForm.php, productivity/projects.php, productivity/retrieveTaskCards.php
changed the test project file to a json so cards can be handled easier
=> txt to json

navbar.php, productivity/editTaskStatus.php, productivity/processAddTaskForm.php, productivity/projects.php
We can now edit tasks, just click on a task and you will be able to change status of the task. Give it a manual test and let me know if it works for you.
=> Ltp 31 add functionality to edit a tasks status

dashboard/adminDashboard.php, generalFiles/users.json, generalFiles/users.txt, login/login.php, navbar.php, register/register.php, register/registerProcess.php
All registered users are by default a normal user. The only admin account is admin@make-it-all.com.
The dashboard being displayed in the navbar.php depends on whether the Session variable 'isAdmin' is true or not.
We can add functionality for a admin to 'upgrade' a user's account at a later point.
=> Added Functionality of User vs Admin accounts.

knowledge/forum.php, navbar.php, style.css
Let me know what you think, this is the basic outline for our knowledge forum.
=> Template for forum

knowledge/forum.php
Easy fix, just added the CSS for it. Was having some issues sticking the style in the CSS file hence why it is inline, any ideas on why this could be ? --> We can always address this post prototype
=> table scrollable

knowledge/addFaq.php, knowledge/faq.php, knowledge/forum.php, knowledge/retrieveFaq.php, style.css
We now have a FAQ page. This is a basic idea that I have added (we can add more to this when we implement the whole thing.
In future I was thinking of adding features such as - 
1. Only admins can make new FAQ
2. Filtering by FAQ
3. Images can be added to FAQ for visual guidence
For now all we have is the question the answer and its linked topics.
=> FAQ page added

knowledge/forum.php, register/register.php
We can now filter by search. I have also fixed the css isue with registration. We also have a no results banner now.
=> Ltp 36 filter by search

knowledge/forum.php
As we are not using it now I have removed it from the code
=> Removed postAge

login/emailFinder.php, login/forgotPassword.php, login/resetDB.php, login/resetPassword.php, register/register.php
Now when the user clicks on the forgot password button they will see -
1. A Screen telling them to enter their password - 
If they have a valid email (one in the system) it will 
2. Send the user an email -
3. When the user clicks on the link it create a forgotPassword code (one time use only) which will help us identify which user is resetting their password. 
4. They will then be on a reset password screen where if the password is strong enough and matches the validate password they will reset their password can can return to the login screen - 
Give it a play, it works for me however it may not work for you. Keep in mind this is working of sci-project so this will all be moved to google cloud in a short time.
=> forgotPassword

admin/viewUsers.php, knowledge/faq.php, knowledge/forum.php, productivity/projects.php
We had some strange issues with the aspect ratio but they are now fixed.
Some of the knowledge wiki is not working, I have left this as I think that it is outside of the scope for this PR (as we will be changing this anyway).
=> bootstrap added

knowledge/deleteTopic.php, knowledge/wiki.php, style.css
- Added some styling for the sidebar.
-  If admin and right clicking on topic you can now delete topics
Give it a test and let me know if all works, also would like some help thinking of how we would like to structure the posts associated with each topic.
=> Modify topics knowledge

.gitignore, productivity/projects.js, productivity/projects.php, productivity/updateTaskStatus.php
Status changes to tasks can now be done via drag and drop with areas showing where to drop tasks. Changes are saved in DB also. Give it a test!
=> Task Status can now be updated via Drag and Drop

knowledge/wiki.php
We now have multiple pages for the topics, please give it a test!
The style is a ruff but the logic is down which is important.
If you dont have the test data just make lots of topics as admin and see if you can change page.
=> multi page

faq/addFaq.php, faq/faq.css, faq/faq.js, faq/faq.php, faq/get.php, knowledge/wiki.php
I have added the basic features of FAQ. Please let me know if there is anything you would have added as I can do this.
What has been added 
- FAQ
- Add FAQ
- Images to Answers
What could be added - 
- delete FAQ
- optional image choice 
As always give it a test and let me know how it goes
=> faqPageAdded

productivity/projects.css, productivity/projects.js, productivity/projects.php
Should display a visual proportion of tasks of the project and also popovers to give further stat info upon hover.
Give it a try and lmk how it works.
=> Progress Bar for Projects

dashboard/adminDashboard.js, dashboard/adminDashboard.php, dashboard/dashboard.js, dashboard/dashboard.php, dashboard/grabProjectCards.php, productivity/databasePHPFiles/addAssignee.php, productivity/databasePHPFiles/deleteTask.php, productivity/databasePHPFiles/getAssignees.php, productivity/databasePHPFiles/processAddTaskForm.php, productivity/databasePHPFiles/processEditTaskForm.php, productivity/databasePHPFiles/removeAssignee.php, productivity/databasePHPFiles/retrieveNonUserAssignedTaskCards.php, productivity/databasePHPFiles/retrieveTaskCards.php, productivity/databasePHPFiles/retrieveTaskDetails.php, productivity/databasePHPFiles/retrieveUserAssignedTaskCards.php, productivity/databasePHPFiles/updateTaskStatus.php, productivity/projects.css, productivity/projects.php, productivity/userProjects.js
Sorry for the loaded PR but as the deadline comes close and we have a lot of unfinished functionality, I think it warrants it.
This PR was to target the user with what they can and can't do on the system. Now, only projects that they are a part of (i.e. have at least one assigned task on) will be presented to them and can be looked at rather than every project like the Admin.
Also, only tasks that the user is assigned to can be edited and other tasks on the project are read only and CANNOT be dragged (I'd like to add a commenting system onto tasks but we'll have to see with time constraints). 
Have a look at the user functionality with the user@make-it-all.com account (password: User1234! if you have forgot) and lmk if it all works.
Future Plans:
- Implement Project Leader Functionality
- …
=> User Interface for Projects

dashboard/adminDashboard.php, dashboard/dashboard.css, dashboard/dashboard.js, dashboard/dashboard.php
Simple redesign of the User dashboard, now looks similar to the Admin dashboard.
- Next feature to add is for To-Do list to save on the User dashboard
=> User Dashboard Redesign

productivity/databasePHPFiles/grabProjectDeadline.php, productivity/projects.css, productivity/projects.js, productivity/projects.php, productivity/userProjects.js
Deadlines are now presented both through text and a dynamic progress bar.
Future Plan:
- Request extension to deadline
=> Deadline of Project is now Shown

admin/grabProjectStats.php, dashboard/dashboard.css, dashboard/graph.js, dashboard/projectStats.php
Let me know if you would like me to implement any more stats or different types of graphs.
=> Added Doughnut Chart and bar chart.

admin/grabProjectStats.php, admin/grabUsersByProject.php, dashboard/adminDashboard.js, dashboard/dashboard.css, dashboard/dashboard.js, dashboard/graph.js, dashboard/projectStats.php
Gets the User List for each project by searching through the userTaskMapping for corresponding project IDs
=> Fix user list

faq/faq.js, knowledge/databasePHPFiles/addComment.php, knowledge/databasePHPFiles/addPost.php, knowledge/databasePHPFiles/addTopics.php, knowledge/databasePHPFiles/deletePost.php, knowledge/databasePHPFiles/deleteTopic.php, knowledge/databasePHPFiles/getComments.php, knowledge/databasePHPFiles/getPost.php, knowledge/databasePHPFiles/getPosts.php, knowledge/databasePHPFiles/getTopics.php, knowledge/posts.js, knowledge/wiki.js
Just cleaning up knowledge folder by copying what we did with projects. Then I have added comments to the code I have done in knowledge wiki and FAQ to make documenting a little easier :) 
Just a technical PR so just give the code a read and LMK what you think
=> Comments + file clean up

dashboard/grabProjectCards.php, productivity/projects.css, productivity/projects.php, productivity/userProjects.js
Only the team leader/admin should be able to add projects and also move every task on a project.
=> Team Leaders of Projects is now implemented

productivity/projects.js
Forgot to enable the add task button for the admin after switching projects
=> Small Bug Fix

productivity/databasePHPFiles/deleteProject.php, productivity/projects.css, productivity/projects.js, productivity/projects.php
The admin can now delete projects by going onto the project on the screen then clicking the delete button.
=> Delete Project Button

admin/deleteUser.php, admin/demoteUser.php, admin/generateModalTable.php, admin/promoteUser.php, admin/viewUsers.js, admin/viewUsers.php
An admin should to be able to now promote, demote, delete and view user's projects stats. Try it out by logging into admin then going to the user table
=> The User Table for Admin now has increased functionality.
